### ISSUE TITLE
error when setting $success to true

### ISSUE THREAD

**Issue by cmnstmntmn** [DeuxHuitHuit/backend_action#1]
i have a simple to simple lines of code

```
mail("constantin.angheloiu@thewizards.ro","My subject","body text");
$success = true;
```

all ok when $success is missing, all wrong when is present

SymphonyCMS 2.3.6
backend_action 1.0

![error](https://cloud.githubusercontent.com/assets/2312755/5654978/678efe62-96d1-11e4-9931-88db796e3185.png)

**Comment by nitriques** [comment]
This is really weird... Can you show me the table structure please ?

**Comment by nitriques** [comment]
BTW, you should check Symphony's Email and EmailGateway classes instead of usign php's mail().

**Comment by nitriques** [comment]
Can you also give me the DateFormat in your config.php file please ?

**Comment by cmnstmntmn** [comment]
that's 

```
    ###### REGION ######
    'region' => array(
        'time_format' => 'g:i a',
        'date_format' => 'm/d/Y',
        'datetime_separator' => ' ',
        'timezone' => 'Europe/Bucharest',
    ),
    ########
```

**Comment by cmnstmntmn** [comment]
i found that ..

```
2014-08-21T13:20:46+03:00  (default entry dates)
2015-01-08T01:54:13+0200   (date extension tries to insert)
```

**Comment by cmnstmntmn** [comment]
and the structure

![entry_structure](https://cloud.githubusercontent.com/assets/2312755/5655747/93c9fdb6-96da-11e4-8a7d-38a25048d26c.png)
![entry_](https://cloud.githubusercontent.com/assets/2312755/5655746/93974ace-96da-11e4-8b47-ef9e8c87f205.png)

**Comment by cmnstmntmn** [comment]
is it possible to execute an EMT template ? something like

```
/email-templates/document-status-update/class.document-status-update.php
```

**Comment by nitriques** [comment]
> is it possible to execute an EMT template ? something like

Never tries it, but yeah, it should be possible as long as you require the EMT files into the action file and call the right methods.

**Comment by nitriques** [comment]
1. The table does not have the 1.0 structure. it should only contain 4 cols: https://github.com/DeuxHuitHuit/backend_action/blob/1.0/fields/field.backend_action.php#L407-L416 (looks like you have the 1.1 schema)
2. Can you try to replace the `DateTimeObj::format()` call with `DateTimeObj::format('u')` on this line https://github.com/DeuxHuitHuit/backend_action/blob/1.0/extension.driver.php#L78

**Comment by nitriques** [comment]
@cmnstmntmn So can we close this one ?

**Comment by cmnstmntmn** [comment]
sure ;)

El viernes, 9 de enero de 2015, Nicolas Brassard notifications@github.com
escribió:

> @cmnstmntmn https://github.com/cmnstmntmn So can we close this one ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DeuxHuitHuit/backend_action/issues/1#issuecomment-69376767
> .

## 

thumb typed

**Comment by nitriques** [comment]
Ok Thanks!
